{"nbformat":4,"nbformat_minor":0,"metadata":{"colab":{"provenance":[],"authorship_tag":"ABX9TyNhCScaejGEN6Uc592n9zoo"},"kernelspec":{"name":"python3","display_name":"Python 3"},"language_info":{"name":"python"}},"cells":[{"cell_type":"code","source":["import sys\n","sys.stderr.write('Warning, log file not found starting a new one\\n')"],"metadata":{"id":"UESiqKWEzMlH","executionInfo":{"status":"ok","timestamp":1734291038816,"user_tz":-540,"elapsed":530,"user":{"displayName":"小野宏司","userId":"04731051123647758900"}},"outputId":"f2f120aa-ceaf-4713-877e-f5a8a57c2796","colab":{"base_uri":"https://localhost:8080/"}},"execution_count":2,"outputs":[{"output_type":"stream","name":"stderr","text":["Warning, log file not found starting a new one\n"]}]}]}